### ISSUE TITLE
How can I do only numbers in captcha image(not an issue)

### ISSUE THREAD

**Issue by Dhruvin12** [MagicaFreak/captchas#1]
This isn't really an issue but i had a question. How can I do only numbers instead of letters? Can I even do that?

**Comment by MagicaFreak** [comment]
Yes you can but not in the class settings self.
You can use the rand_chars function with only digits to generate a text and use that text in the captcha like so:
```Python
import string
from bettercaptcha import CaptchaImage

captcha_text = CaptchaImage.rand_chars(8, string.digits)
captcha = CaptchaImage(text=captcha_text)

image = captcha.create()
```
or
```Python
import random
from bettercaptcha import CaptchaImage

captcha_text = str(random.randint(10000000, 99999999))
captcha = CaptchaImage(text=captcha_text)

image = captcha.create()
```
But i will consider to make it possible that you can overwrite the list where the characters are getted from
