### ISSUE TITLE
Getting an error when creating text

### ISSUE THREAD

**Issue by Dhruvin12** [MagicaFreak/captchas#2]
So i recently rented a vps for my discord bot, and when it tries sending a captcha image it sends an error saying "OS Error: Cannot open resource", is there a way to fix that? I downloaded the pypi in the correct folder but it still sends that error.

![Screenshot (112)](https://user-images.githubusercontent.com/77473540/134772312-a1902a2e-9c8f-4931-8787-56712a67cb70.png)

**Comment by MagicaFreak** [comment]
The problem is the font. You could try to set the full path to the font you want to use like: `C:/some/folders/arrial.ttf` or you wait cause i will fix this! Thanks for showing me this bug
